# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# prebuilt docker images with toolchain
executors:
  setup-rv64gc:
    docker:
      - image: keystoneenclaveorg/keystone:init-rv64gc
  setup-rv32gc:
    docker:
      - image: keystoneenclaveorg/keystone:init-rv32gc


commands:
  update-riscv-toolchain-path:
    steps:
      - run: echo 'export PATH=/keystone/riscv64/bin:/keystone/riscv32/bin:$PATH' >> $BASH_ENV

jobs:
  build-and-test-rv64-qemu:
    executor: setup-rv64gc
    working_directory: /keystone/sm
    steps:
      - checkout
      - update-riscv-toolchain-path
      - run:
          name: "Build rv64 and run tests"
          command: |
              mkdir tests/build
              cd tests/build
              cmake ..
              make -j$(nproc)
          no_output_timeout: 120m

workflows:
  build-and-test:
    jobs:
      - build-and-test-rv64-qemu